plugins {
    id 'java'
}

group = 'com.ultraop.nametag'
version = '0.1.0-SNAPSHOT'

subprojects {
    apply plugin: 'java'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
        maven {
            name = 'papermc'
            url = uri('https://repo.papermc.io/repository/maven-public/')
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
