plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.14.10'
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:0.18.1"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.141.3+1.21.11"
    implementation project(':api')
    implementation project(':common')
    implementation project(path: ':versions:fabric-1.21.11', configuration: 'namedElements')
}

tasks.withType(JavaCompile).configureEach { options.release = 21 }
