repositories { maven { url = 'https://repo.papermc.io/repository/maven-public/' } }
dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"
    implementation project(':api')
    implementation project(':common')
    implementation project(':versions:paper-1.21.11')
    testImplementation "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"
    testImplementation "org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.110.0"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

processResources {
    filesMatching('plugin.yml') {
        expand(project: project)
    }
}

tasks.withType(Test).configureEach {
    testLogging {
        exceptionFormat = 'full'
        showStackTraces = true
    }
}
