dependencies {
    implementation project(':api')
    implementation project(':core')
    compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

tasks.withType(JavaCompile).configureEach { options.release = 21 }
